#!/bin/sh
killall -9 containermanagerd 2> /dev/null
killall cfprefsd 2> /dev/null
killall -9 securityd 2> /dev/null
killall pkd 2> /dev/null
killall -9 apsd 2> /dev/null
killall -9 lsd 2> /dev/null
killall -9 accountsd 2> /dev/null

# secondary daemons, affected by accountsd
killall -9 appstored 2> /dev/null
killall -9 itunesstored 2> /dev/null
killall -9 gamed 2> /dev/null

exit 0